const PRODUCTS=[['sand-dune','Sand Dune Latte'],['adeni','Adeni Chai'],['matcha','Palm Date Matcha'],['biscoff','Biscoff Coffee']];
const FEE=200;
export function config(env){let prices={};try{prices=JSON.parse(env.MENU_PRICES_JSON||'{}')}catch{}const delivery=/^\d+$/.test(env.DELIVERY_FEE_CENTS||'')?Number(env.DELIVERY_FEE_CENTS):null;const deliveryFee=Number.isInteger(delivery)&&delivery>=0&&delivery<=10000?delivery:null;const items=PRODUCTS.map(([id,name])=>({id,name,price:Number.isInteger(prices[id])&&prices[id]>0&&prices[id]<=100000?prices[id]:null,image:`assets/${id}.webp`}));return {items,currency:'usd',convenienceFee:FEE,deliveryFee,deliveryZips:(env.DELIVERY_ZIPS||'').split(',').map(s=>s.trim()).filter(s=>/^\d{5}$/.test(s)),orderingEnabled:env.ORDERING_ENABLED==='true'&&!!env.STRIPE_SECRET_KEY&&!!env.ORDER_TOKEN_SECRET&&!!env.ORDER_ADMIN_TOKEN&&!!env.STRIPE_WEBHOOK_SECRET&&env.FULFILLMENT_READY==='true'&&env.TAX_READY==='true'&&items.every(i=>i.price!==null)}}
const json=(body,status=200)=>new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});
export function calculateOrder(input,c){if(!['pickup','delivery'].includes(input.fulfillment))throw Error('Choose pickup or delivery.');if(!Array.isArray(input.items)||!input.items.length||input.items.length>4)throw Error('Add between one and four different drinks.');const seen=new Set();let count=0;const lines=input.items.map(row=>{const product=c.items.find(p=>p.id===row.id);if(!product||product.price===null||seen.has(row.id)||!Number.isInteger(row.quantity)||row.quantity<1||row.quantity>20)throw Error('Invalid item or quantity.');seen.add(row.id);count+=row.quantity;return {...product,quantity:row.quantity}});if(count>40)throw Error('Please call the shop for orders larger than 40 drinks.');if(input.fulfillment==='delivery'&&(c.deliveryFee===null||!c.deliveryZips.includes(input.zip)))throw Error('Delivery is not available for this ZIP code.');const subtotal=lines.reduce((s,l)=>s+l.price*l.quantity,0),deliveryFee=input.fulfillment==='pickup'?0:c.deliveryFee;return {lines,subtotal,deliveryFee,convenienceFee:FEE,total:subtotal+FEE+deliveryFee}}
async function sign(value,secret){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return [...new Uint8Array(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(value)))].map(b=>b.toString(16).padStart(2,'0')).join('')}
function equal(a,b){if(typeof a!=='string'||typeof b!=='string'||a.length!==b.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=a.charCodeAt(i)^b.charCodeAt(i);return d===0}
async function stripe(env,path,body,idempotency){const headers={Authorization:`Bearer ${env.STRIPE_SECRET_KEY}`};if(body)headers['Content-Type']='application/x-www-form-urlencoded';if(idempotency)headers['Idempotency-Key']=idempotency;const r=await fetch('https://api.stripe.com/v1/'+path,{method:body?'POST':'GET',headers,body:body?new URLSearchParams(body):undefined,signal:AbortSignal.timeout(12000)});if(!r.ok)throw Error('Payment service is temporarily unavailable. Please try again.');return r.json()}
export async function verifyWebhook(raw,header,secret,now=Date.now()){const parts=header.split(',').map(x=>x.split('='));const t=parts.find(x=>x[0]==='t')?.[1],sigs=parts.filter(x=>x[0]==='v1').map(x=>x[1]);if(!t||!/^\d+$/.test(t)||Math.abs(now/1000-Number(t))>300)return false;const expected=await sign(t+'.'+raw,secret);return sigs.some(s=>equal(s,expected))}
export async function commerce(request,env){const u=new URL(request.url),c=config(env);if(u.pathname==='/api/catalog'&&request.method==='GET')return json(c);
try{
if(u.pathname==='/api/checkout'&&request.method==='POST'){
if(!c.orderingEnabled)return json({error:'Online ordering is not available yet. Please call the shop.'},503);
if(request.headers.get('origin')!==u.origin)return json({error:'Invalid request origin.'},403);
const raw=await request.text();if(raw.length>5000)return json({error:'Request too large.'},413);const input=JSON.parse(raw),quote=calculateOrder(input,c);if(input.fulfillment==='delivery'&&(!input.address||!['name','street','city'].every(k=>typeof input.address[k]==='string'&&input.address[k].trim().length>=2&&input.address[k].length<=160)||!/^[A-Z]{2}$/.test(input.address.state||'')))return json({error:'Enter the recipient name and complete delivery address.'},400);
if(!/^[a-f0-9-]{36}$/.test(input.attemptId||''))return json({error:'Invalid checkout attempt.'},400);
const fingerprint=JSON.stringify({items:quote.lines.map(x=>[x.id,x.quantity,x.price]),mode:input.fulfillment,zip:input.zip,delivery:quote.deliveryFee,address:input.address});const hash=await sign(fingerprint,env.ORDER_TOKEN_SECRET);const reference=input.attemptId.slice(0,8).toUpperCase();const token=await sign(input.attemptId+hash,env.ORDER_TOKEN_SECRET);
const body={'mode':'payment','payment_method_types[0]':'card','success_url':u.origin+'/?session_id={CHECKOUT_SESSION_ID}#order_token='+token,'cancel_url':u.origin+'/?checkout=cancelled#menu','automatic_tax[enabled]':'true','billing_address_collection':'required','phone_number_collection[enabled]':'true','metadata[arwa_order]':'true','metadata[reference]':reference,'metadata[fulfillment]':input.fulfillment,'metadata[order_token]':token,'metadata[delivery_zip]':input.zip||'','metadata[status]':'Order received','payment_intent_data[metadata][arwa_order]':reference,'payment_intent_data[metadata][fulfillment]':input.fulfillment,'payment_intent_data[description]':'Arwa '+input.fulfillment+' order '+reference};
const lines=[...quote.lines.map(l=>({name:l.name,amount:l.price,quantity:l.quantity})),{name:'Convenience fee',amount:FEE,quantity:1}];if(input.fulfillment==='delivery'){lines.push({name:'Delivery fee',amount:quote.deliveryFee,quantity:1});body['metadata[delivery_address]']=JSON.stringify({...input.address,zip:input.zip});body['payment_intent_data[metadata][delivery_address]']=JSON.stringify({...input.address,zip:input.zip});body['custom_text[submit][message]']='Deliver to '+input.address.street+', '+input.address.city+', '+input.address.state+' '+input.zip+'.';}
lines.forEach((l,i)=>{body[`line_items[${i}][price_data][currency]`]='usd';body[`line_items[${i}][price_data][product_data][name]`]=l.name;body[`line_items[${i}][price_data][unit_amount]`]=String(l.amount);body[`line_items[${i}][price_data][tax_behavior]`]='exclusive';body[`line_items[${i}][quantity]`]=String(l.quantity)});

const addr=input.fulfillment==='delivery'?input.address:{name:'Arwa pickup',street:'1953 N Milwaukee Ave',city:'Chicago',state:'IL'};const taxZip=input.fulfillment==='delivery'?input.zip:'60647';const customer=await stripe(env,'customers',{'shipping[name]':addr.name,'shipping[address][line1]':addr.street,'shipping[address][city]':addr.city,'shipping[address][state]':addr.state,'shipping[address][postal_code]':taxZip,'shipping[address][country]':'US'},'arwa-customer-'+input.attemptId+'-'+hash);body.customer=customer.id;body['customer_update[address]']='auto';
const session=await stripe(env,'checkout/sessions',body,'arwa-'+input.attemptId+'-'+hash);return json({url:session.url});}
if(u.pathname==='/api/order'&&request.method==='GET'){
if(!env.STRIPE_SECRET_KEY)return json({error:'Ordering is not configured.'},503);const id=u.searchParams.get('session');if(!/^cs_(test_|live_)?[A-Za-z0-9]+$/.test(id||''))return json({error:'Invalid order.'},400);const session=await stripe(env,'checkout/sessions/'+encodeURIComponent(id));if(session.metadata?.arwa_order!=='true'||!equal(request.headers.get('authorization'),'Bearer '+session.metadata.order_token))return json({error:'Order not found.'},404);const paid=session.payment_status==='paid';return json({paid,reference:session.metadata.reference,fulfillment:session.metadata.fulfillment,status:paid?session.metadata.status:'Awaiting payment',total:session.amount_total});}
if(u.pathname==='/api/staff/orders'&&request.method==='GET'){
if(!env.ORDER_ADMIN_TOKEN||!equal(request.headers.get('authorization'),'Bearer '+env.ORDER_ADMIN_TOKEN))return json({error:'Unauthorized.'},401);const sessions=await stripe(env,'checkout/sessions?limit=50');return json({orders:sessions.data.filter(s=>s.metadata?.arwa_order==='true'&&s.payment_status==='paid').map(s=>({session:s.id,reference:s.metadata.reference,fulfillment:s.metadata.fulfillment,status:s.metadata.status,total:s.amount_total,created:s.created,address:s.metadata.delivery_address||null,email:s.customer_details?.email||null})),hasMore:sessions.has_more});}
if(u.pathname==='/api/order/status'&&request.method==='POST'){
if(!env.ORDER_ADMIN_TOKEN||!equal(request.headers.get('authorization'),'Bearer '+env.ORDER_ADMIN_TOKEN))return json({error:'Unauthorized.'},401);const input=await request.json();if(!/^cs_(test_|live_)?[A-Za-z0-9]+$/.test(input.session||''))return json({error:'Invalid order.'},400);const session=await stripe(env,'checkout/sessions/'+encodeURIComponent(input.session));if(session.metadata?.arwa_order!=='true'||session.payment_status!=='paid')return json({error:'Paid Arwa order required.'},409);const sequence=session.metadata.fulfillment==='delivery'?['Order received','Making your order','Ready for delivery','On the way','Arrived']:['Order received','Making your order','Ready for pickup','Picked up'];const current=sequence.indexOf(session.metadata.status);if(input.status!==sequence[current+1])return json({error:'Only the next fulfillment step is allowed.'},409);await stripe(env,'checkout/sessions/'+encodeURIComponent(input.session),{'metadata[status]':input.status});return json({status:input.status});}
if(u.pathname==='/api/stripe/webhook'&&request.method==='POST'){
if(!env.STRIPE_WEBHOOK_SECRET)return json({error:'Webhook not configured.'},503);const raw=await request.text();if(raw.length>1000000)return json({error:'Payload too large.'},413);if(!await verifyWebhook(raw,request.headers.get('stripe-signature')||'',env.STRIPE_WEBHOOK_SECRET))return json({error:'Invalid signature.'},400);const event=JSON.parse(raw);if(event.type==='checkout.session.completed'&&event.data.object.payment_status==='paid'&&event.data.object.metadata?.arwa_order==='true'){await stripe(env,'checkout/sessions/'+event.data.object.id,{'metadata[payment_confirmed]':'true'});}return json({received:true});}
return json({error:'Not found.'},404);
}catch(e){return json({error:e instanceof SyntaxError?'Invalid request.':e.message||'Service unavailable.'},400)}}
